package com.pi4j.io.pwm;

import java.util.EnumSet;

/**
 * Enumerates the kind of PWM generator backing a {@link Pwm} instance, as configured
 * via {@link PwmConfig#pwmType()} and {@link PwmConfigBuilder#pwmType(PwmType)}.
 * Not all providers support both generator types.
 */
public enum PwmType {
    /** PWM signal generated in software (e.g. by toggling a GPIO pin); typically driven by a BCM pin. */
    SOFTWARE(0, "software"),
    /** PWM signal generated by a dedicated hardware peripheral; addressed by chip and channel. */
    HARDWARE(1, "hardware");

    private final int value;
    private final String name;

    private PwmType(int value, String name) {
        this.value = value;
        this.name = name;
    }

    /**
     * Returns the numeric code of this type (0 for {@link #SOFTWARE}, 1 for {@link #HARDWARE}).
     *
     * @return the numeric type code
     */
    public int getValue() {
        return value;
    }

    /**
     * Returns the lower-case textual name of this type ({@code "software"} or {@code "hardware"}).
     *
     * @return the type name
     */
    public String getName() {
        return name;
    }

    @Override
    public String toString() {
        return name.toUpperCase();
    }

    /**
     * Returns a set containing every defined PWM type.
     *
     * @return an {@link EnumSet} of all {@link PwmType} values
     */
    public static EnumSet<PwmType> all() {
        return EnumSet.allOf(PwmType.class);
    }

    /**
     * Parses a PWM type from a string. Accepts the numeric codes {@code "0"}/{@code "1"}
     * or any value starting with {@code 'h'} (hardware) or {@code 's'} (software),
     * case-insensitively; any unrecognized value defaults to {@link #SOFTWARE}.
     *
     * @param pwmType the PWM type text to parse
     * @return the matching type, or {@link #SOFTWARE} if not recognized
     */
    public static PwmType parse(String pwmType) {
        if(pwmType.equalsIgnoreCase("0")) return PwmType.SOFTWARE;
        if(pwmType.equalsIgnoreCase("1")) return PwmType.HARDWARE;
        if(pwmType.toLowerCase().startsWith("h")) return PwmType.HARDWARE;
        if(pwmType.toLowerCase().startsWith("s")) return PwmType.SOFTWARE;
        return PwmType.SOFTWARE; // default
    }
}
