package com.pi4j.io.pwm;

import java.util.EnumSet;

/*
 * #%L
 * **********************************************************************
 * ORGANIZATION  :  Pi4J
 * PROJECT       :  Pi4J :: LIBRARY  :: Java Library (CORE)
 * FILENAME      :  PwmType.java
 *
 * This file is part of the Pi4J project. More information about
 * this project can be found here:  https://pi4j.com/
 * **********************************************************************
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

/**
 * Enumerates the kind of PWM generator backing a {@link Pwm} instance, as configured
 * via {@link PwmConfig#pwmType()} and {@link PwmConfigBuilder#pwmType(PwmType)}.
 * Not all providers support both generator types.
 */
public enum PwmType {
    /** PWM signal generated in software (e.g. by toggling a GPIO pin); typically driven by a BCM pin. */
    SOFTWARE(0, "software"),
    /** PWM signal generated by a dedicated hardware peripheral; addressed by chip and channel. */
    HARDWARE(1, "hardware");

    private final int value;
    private final String name;

    private PwmType(int value, String name) {
        this.value = value;
        this.name = name;
    }

    /**
     * Returns the numeric code of this type (0 for {@link #SOFTWARE}, 1 for {@link #HARDWARE}).
     *
     * @return the numeric type code
     */
    public int getValue() {
        return value;
    }

    /**
     * Returns the lower-case textual name of this type ({@code "software"} or {@code "hardware"}).
     *
     * @return the type name
     */
    public String getName() {
        return name;
    }

    @Override
    public String toString() {
        return name.toUpperCase();
    }

    /**
     * Returns a set containing every defined PWM type.
     *
     * @return an {@link EnumSet} of all {@link PwmType} values
     */
    public static EnumSet<PwmType> all() {
        return EnumSet.allOf(PwmType.class);
    }

    /**
     * Parses a PWM type from a string. Accepts the numeric codes {@code "0"}/{@code "1"}
     * or any value starting with {@code 'h'} (hardware) or {@code 's'} (software),
     * case-insensitively; any unrecognized value defaults to {@link #SOFTWARE}.
     *
     * @param pwmType the PWM type text to parse
     * @return the matching type, or {@link #SOFTWARE} if not recognized
     */
    public static PwmType parse(String pwmType) {
        if(pwmType.equalsIgnoreCase("0")) return PwmType.SOFTWARE;
        if(pwmType.equalsIgnoreCase("1")) return PwmType.HARDWARE;
        if(pwmType.toLowerCase().startsWith("h")) return PwmType.HARDWARE;
        if(pwmType.toLowerCase().startsWith("s")) return PwmType.SOFTWARE;
        return PwmType.SOFTWARE; // default
    }
}
